//!Color Hexes//
const Colors = {
    get random() { return Math.floor(Math.random() * 0xFFFFFF); },
    gold: 0xFFD700,
    orange: 0xFFA500,
    red: 0xDC143C,
    green: 0x008000,
    white: 0xFFFFFF,
    black: 0x000000,
    brown: 0x8B4513,
    pink: 0xFFC0CB,
    hotPink: 0xFF69B4,
    deepPink: 0xFF1493,
    violet: 0xEE82EE,
    magenta: 0xFF00FF,
    darkViolet: 0x9400D3,
    purple: 0x800080,
    indigo: 0x4B0082,
    maroon: 0x800000,
    cyan: 0x00FFFF,
    teal: 0x008080,
    blue: 0x0000FF
};

//! Disabled Events//
const DisabledEvents = {
    GUILD_UPDATE: true,
    CHANNEL_CREATE: true,
    CHANNEL_UPDATE: true,
    CHANNEL_DELETE: true,
    CHANNEL_OVERWRITE_CREATE: true,
    CHANNEL_OVERWRITE_UPDATE: true,
    CHANNEL_OVERWRITE_DELETE: true,
    MEMBER_KICK: true,
    MEMBER_PRUNE: true,
    MEMBER_BAN_ADD: true,
    MEMBER_BAN_REMOVE: true,
    MEMBER_UPDATE: false,
    MEMBER_ROLE_UPDATE: false,
    MEMBER_MOVE: true,
    MEMBER_DISCONNECT: true,
    BOT_ADD: true,
    ROLE_CREATE: true,
    ROLE_UPDATE: true,
    ROLE_DELETE: true,
    INVITE_CREATE: true,
    INVITE_UPDATE: true,
    INVITE_DELETE: true,
    WEBHOOK_CREATE: true,
    WEBHOOK_UPDATE: true,
    WEBHOOK_DELETE: true,
    EMOJI_CREATE: true,
    EMOJI_UPDATE: true,
    EMOJI_DELETE: true,
    MESSAGE_CREATE: false,
    MESSAGE_DELETE: true,
    MESSAGE_BULK_DELETE: true,
    MESSAGE_PIN: true,
    MESSAGE_UNPIN: true,
    INTEGRATION_CREATE: true,
    INTEGRATION_UPDATE: true,
    INTEGRATION_DELETE: true,
    STAGE_INSTANCE_CREATE: true,
    STAGE_INSTANCE_UPDATE: true,
    STAGE_INSTANCE_DELETE: true,
    STICKER_CREATE: true,
    STICKER_UPDATE: true,
    STICKER_DELETE: true,
    GUILD_SCHEDULED_EVENT_CREATE: true,
    GUILD_SCHEDULED_EVENT_UPDATE: true,
    GUILD_SCHEDULED_EVENT_DELETE: true,
    THREAD_CREATE: true,
    THREAD_UPDATE: true,
    THREAD_DELETE: true,
    APPLICATION_COMMAND_PERMISSION_UPDATE: true,
};

const ColorLogs = {
    Reset: "\x1b[0m",
    Bright: "\x1b[1m",
    Dim: "\x1b[2m",
    Underscore: "\x1b[4m",
    Blink: "\x1b[5m",
    Reverse: "\x1b[7m",
    Hidden: "\x1b[8m",
    FgBlack: "\x1b[30m",
    FgRed: "\x1b[31m",
    FgGreen: "\x1b[32m",
    FgYellow: "\x1b[33m",
    FgBlue: "\x1b[34m",
    FgMagenta: "\x1b[35m",
    FgCyan: "\x1b[36m",
    FgWhite: "\x1b[37m",
    BgBlack: "\x1b[40m",
    BgRed: "\x1b[41m",
    BgGreen: "\x1b[42m",
    BgYellow: "\x1b[43m",
    BgBlue: "\x1b[44m",
    BgMagenta: "\x1b[45m",
    BgCyan: "\x1b[46m",
    BgWhite: "\x1b[47m",

}

export { ColorLogs as ColorLogs };
export { Colors as Colors };
export { DisabledEvents as DisabledEvents }